### ISSUE TITLE
Postgres not coming up

### ISSUE THREAD

**Issue by johlton** [rdmorganiser/rdmo-docker-compose#21]
I'm running into problems using the current version for a 2nd docker instance on the same machine. Another older version of the docker-compose instance on the same machine works fine.

1. Edited the `variables.local`
2. Run `make` 

`make` then stops with the following message:
````
Configuring postgresql-common
-----------------------------

createcluster.conf: A new version (/tmp/postgresql-common.TeWQyR) of
configuration file /etc/postgresql-common/createcluster.conf is available, but
the version installed currently has been locally modified.

  1. install the package maintainer's version
  2. keep the local version currently installed
  3. show the differences between the versions
  4. show a side-by-side difference between the versions
  5. start a new shell to examine the situation
What do you want to do about modified configuration file createcluster.conf?
````

Since its running in non-interactive mode, none of the choices gets submitted. I then followed https://stackoverflow.com/a/72273217/6948765 and added `DEBIAN_FRONTEND=noninteractive` as env variable. This fixes the config prompt.

The postgres container gets built, but doesn't start properly. I dont know if it's related at all. `docker logs` shows:

````
initdb: error: invalid locale settings; check LANG and LC_* environment variables
chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted
chmod: changing permissions of '/var/run/postgresql': Operation not permitted
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
````

And this is where I'm a bit lost. The created volume under `/vol/` has the owner `systemd-coredump` but I cant make anything of it.

Any idea? Thanks!

**Comment by triole** [comment]
Hi,
your problem description looks quite strange to me. I have the suspicion that a probable cause might be that you tried to run the two different docker-compose instances from a single cloned repo folder. Postgres and all the other volumes are created on your host machine inside the `vol` folder. Starting two instances from one repo folder would lead to both accessing the exactly same database files on your host. This can't work and would explain your modified postgres conf error message.

Currently rdmo-docker-compose needs a repo clone for every instance. It was designed this way because we wanted to have a clear distinction between instances even on the host level to be able to make specific adjustments for running different versions or other experiments. 

Please intervene if I assessed your workflow wrong. I'd restart examining the error then.

Regards.

**Comment by johlton** [comment]
Hey, no, it's separated. 2 repo clones in two different directories. Different ports, too. I totally agree with this clear distinction, everything else would be a mess. `docker-compose.yml` is structurally not different from `dc_master.yaml` and the container names are distinguished from the 1st instance:

````
version: "3.8"

services:
    postgres:
        build:
            context: ./docker/postgres
            args:
                UID: 1004
        container_name: rdc-foobar-postgres
        restart: "always"
        volumes:
            - postgres:/var/lib/postgresql/data
        env_file:
            - variables.local
    [...]
        
volumes:
    postgres:
        name: rdc-foobar-postgres
        driver_opts:
            type: none
            device: /srv/rdmo-foobar/vol/postgres
            o: bind
    [...]        
````        

I researched the ownership once more and found this on [stackoverflow](https://askubuntu.com/a/1267298/912117):

> On Ubuntu 18.04 and before the docker group had gid 999 but in Ubuntu 20.04 that gid is now taken by systemd-coredump. The docker group now seems to default to gid 998. This creates incompatibilities when operating across different versions of Ubuntu.

Thanks for having a look.
